name: Reusable Deploy Template

on:
  workflow_call:
    inputs:
      target_branch:
        description: 'Branch to deploy'
        type: string
        required: false
      is_dispatch:
        description: 'Is this triggered by a library update?'
        type: boolean
        required: false
        default: false
      environment_target:
        description: 'Target environment (prod or test)'
        type: string
        required: false
    secrets:
      SUBMODULE_TOKEN:
        required: false
      PROD_UNIVERSE_ID:
        required: false
      PROD_PLACE_ID:
        required: false
      TEST_UNIVERSE_ID:
        required: false
      TEST_PLACE_ID:
        required: false
      ROBLOX_API_KEY:
        required: false

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.SUBMODULE_TOKEN || github.token }}

      - name: Update Submodules
        if: ${{ inputs.is_dispatch == true }}
        run: |
          git submodule update --remote --merge
          git submodule foreach "git checkout ${{ inputs.target_branch }} || true"

      - name: Install Rojo
        uses: ok-nick/setup-aftman@v0.4.2

      - name: Build Place File
        run: rojo build -o place.rbxl

      - name: Determine Target Environment
        id: target
        run: |
          IS_PROD="false"
          if [ "${{ github.event_name }}" == "push" ] && [ "${{ github.ref }}" == "refs/heads/master" ]; then
            IS_PROD="true"
          elif [ "${{ inputs.is_dispatch }}" == "true" ] && [ "${{ inputs.environment_target }}" == "prod" ]; then
            IS_PROD="true"
          fi
          echo "is_prod=$IS_PROD" >> "$GITHUB_OUTPUT"

      - name: Publish to Official (PROD)
        if: steps.target.outputs.is_prod == 'true'
        run: |
          echo "Pushing to Official Place"
          curl --fail --location --request POST "https://apis.roblox.com/universes/v1/${{ secrets.PROD_UNIVERSE_ID }}/places/${{ secrets.PROD_PLACE_ID }}/versions?versionType=Published" \
            --header "x-api-key: ${{ secrets.ROBLOX_API_KEY }}" \
            --header "Content-Type: application/octet-stream" \
            --data-binary "@place.rbxl"

      - name: Publish to Test Place (TEST)
        if: steps.target.outputs.is_prod == 'false'
        run: |
          echo "Pushing to Test Place"
          curl --fail --location --request POST "https://apis.roblox.com/universes/v1/${{ secrets.TEST_UNIVERSE_ID }}/places/${{ secrets.TEST_PLACE_ID }}/versions?versionType=Published" \
            --header "x-api-key: ${{ secrets.ROBLOX_API_KEY }}" \
            --header "Content-Type: application/octet-stream" \
            --data-binary "@place.rbxl"
